# 비용 함수 구현

In [1]:
import torch
import torch.nn.functional as F
torch.manual_seed(1)

In [2]:
z = torch.FloatTensor([1, 2, 3])


In [3]:
hypothesis = F.softmax(z, dim=0)
print(hypothesis)

tensor([0.0900, 0.2447, 0.6652])


In [4]:
hypothesis.sum()

tensor(1.)

In [5]:
z = torch.rand(3, 5, requires_grad=True) # 3 x 5 텐서

In [6]:
hypothesis = F.softmax(z, dim=1)
print(hypothesis) # 3개의 샘플에 대해 5개의 클래스 중 어떤 클래스가 정답인지

tensor([[0.2645, 0.1639, 0.1855, 0.2585, 0.1277],
        [0.2430, 0.1624, 0.2322, 0.1930, 0.1694],
        [0.2226, 0.1986, 0.2326, 0.1594, 0.1868]], grad_fn=<SoftmaxBackward0>)


In [8]:
y = torch.randint(5, (3,)).long() # 각 샘플에 대한 임의의 레이블
print(y)

tensor([2, 1, 0])


In [9]:
y_one_hot = torch.zeros_like(hypothesis)
y_one_hot.scatter_(1, y.unsqueeze(1), 1)

tensor([[0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0.]])

In [10]:
cost = (y_one_hot * -torch.log(hypothesis)).sum(dim=1).mean()
print(cost)

tensor(1.6682, grad_fn=<MeanBackward0>)


# High level 구현

In [11]:
(y_one_hot * - F.log_softmax(z, dim=1)).sum(dim=1).mean()

tensor(1.6682, grad_fn=<MeanBackward0>)

In [12]:
F.nll_loss(F.log_softmax(z, dim=1), y) # negative log likelihood

tensor(1.6682, grad_fn=<NllLossBackward0>)

In [13]:
F.cross_entropy(z, y) # cross entropy

tensor(1.6682, grad_fn=<NllLossBackward0>)