# nn.Module로 구현하는 로지스틱 회귀

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
torch.manual_seed(1)

In [2]:
x_data = [[1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2]]
y_data = [[0], [0], [0], [1], [1], [1]]
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

In [3]:
model = nn.Sequential(
    nn.Linear(2, 1),
    nn.Sigmoid() # 출력은 시그모이드 함수를 거침
)

In [4]:
model(x_train) # 랜덤 초기화 상태

tensor([[0.4020],
        [0.4147],
        [0.6556],
        [0.5948],
        [0.6788],
        [0.8061]], grad_fn=<SigmoidBackward0>)

In [5]:
optimizer = optim.SGD(model.parameters(), lr=0.1)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):
    hypothesis = model(x_train)
    cost = F.binary_cross_entropy(hypothesis, y_train)
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100 == 0:
        prediction = hypothesis >= torch.FloatTensor([0.5])
        correct_prediction = prediction.float() == y_train
        accuracy = correct_prediction.sum().item() / len(correct_prediction) # 정확도
        print('Epoch {:4d}/{} Cost: {:.6f} Accuracy: {:2.2f}'.format(
            epoch, nb_epochs, cost.item(), accuracy * 100))

Epoch    0/1000 Cost: 0.539713 Accuracy: 83.33
Epoch  100/1000 Cost: 0.407688 Accuracy: 83.33
Epoch  200/1000 Cost: 0.345649 Accuracy: 83.33
Epoch  300/1000 Cost: 0.298323 Accuracy: 83.33
Epoch  400/1000 Cost: 0.261179 Accuracy: 83.33
Epoch  500/1000 Cost: 0.231633 Accuracy: 100.00
Epoch  600/1000 Cost: 0.207779 Accuracy: 100.00
Epoch  700/1000 Cost: 0.188230 Accuracy: 100.00
Epoch  800/1000 Cost: 0.171976 Accuracy: 100.00
Epoch  900/1000 Cost: 0.158282 Accuracy: 100.00
Epoch 1000/1000 Cost: 0.146605 Accuracy: 100.00


In [7]:
print(model(x_train))
print(y_train)

tensor([[0.0295],
        [0.1571],
        [0.2988],
        [0.7841],
        [0.9413],
        [0.9808]], grad_fn=<SigmoidBackward0>)
tensor([[0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.]])


In [8]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.4849, 0.3290]], requires_grad=True), Parameter containing:
tensor([-5.6365], requires_grad=True)]
